### PR TITLE
fix: fixing readme link

### PR DESCRIPTION
**Pull request by majewskim**
## What does this change?

Fixing a link in the README.md file

## How was this tested?

How have you tested your changes?
Ways of testing could include:

- Writing or extending an end to end test
- Testing your change on a preview deployment

## Accessibility

If applicable to your changes, have you:

- [ ] Tested with screen reader
- [ ] Checked to see if navigable by keyboard
- [ ] Ensured that the colour contrast is passing

## Documentation

If applicable to your changes, have you:

- [ ] Added/edited the appropriate documentation
- [ ] Added any component(s) to Storybook

### CODE REVIEW

**Comment by marxian** [comment]
Hey @majewskim! Welcome and thank you :-)

**Review by ob6160 — COMMENTED** [review]
happy with the change to the list formatting, but the readme link fix doesn't seem to be included in the PR yet

**Comment by majewskim** [comment]
I renamed the file "[.github/CODE_OF_CONDUCT → .github/CODE_OF_CONDUCT.md] because it was resolving in a 404.
Not really obvious in the commit log haha

**Review by ob6160 — APPROVED** [review]

**Comment by ob6160** [comment]
> I renamed the file "[.github/CODE_OF_CONDUCT → .github/CODE_OF_CONDUCT.md] because it was resolving in a 404. Not really obvious in the commit log haha

ah I see, approved :)

**Review by ob6160 — APPROVED** [review]

**Pull request merged**
