### PR TITLE
Mobile improvements

### PR DESCRIPTION
**Pull request by majewskim**
## What does this change?

Two mobile usability improvements.
1. Enabling map controls on mobile devices2. 
2. Automatically zooming out the map after finding user's location to show pins around.
 
## How was this tested?

Manual testing

## Accessibility

If applicable to your changes, have you:

- [ ] Tested with screen reader
- [ ] Checked to see if navigable by keyboard
- [ ] Ensured that the colour contrast is passing

## Documentation

If applicable to your changes, have you:

- [ ] Added/edited the appropriate documentation
- [ ] Added any component(s) to Storybook

### CODE REVIEW

**Comment by marxian** [comment]
Thanks @majewskim we'll take a good look in the morning :-)

**Comment by ob6160** [comment]
thanks so much for the contribution, really appreciate it :) 
will take a look at this next week!

**Review by ob6160 — COMMENTED** [review]
Hi! I'm waiting for a plane (got here way too early) so taking the chance to put a review on this (and give some context about why things are the way they are) 

Both of these changes seem like great improvements to general UX on mobile — the change to the zoom level on geolocation especially. 

if i remember correctly, the controls were intentionally hidden on mobile viewports in favour of pinch to zoom and the "find a toilet near me" button. @marxian or @rosejbon might have more context  around the reasoning here, as i believe Rose worked on adding this (and related tracking)

I did just try out the controls on my mobile and it seems like a good experience, it's worth mentioning that the viewport on my mobile is a bit larger than average. For users on smaller devices, it could maybe occlude valuable map space perhaps?

Zooming out on mobile devices is a much needed fix, it's been bugging me for a while :)

So, i'm happy with the changes, but keep to hear what others think. out of interest, what prompted you to want the controls on mobile?

**Comment by majewskim** [comment]
So since that PR I actually made this much better.
Now it's completely dynamic based on neighbours of the user's location.
https://github.com/majewskim/toiletmap/commit/46d2e895860f3a28fc3a3905ee848a479dac9506

Maybe I'll open that PR instead :)

**Comment by ob6160** [comment]
> So since that PR I actually made this much better. Now it's completely dynamic based on neighbours of the user's location. [majewskim@46d2e89](https://github.com/majewskim/toiletmap/commit/46d2e895860f3a28fc3a3905ee848a479dac9506)
> 
> Maybe I'll open that PR instead :)

ooooh, looks like a great idea! look forward to seeing the PR :)

**Comment by majewskim** [comment]
Just opened a new PR with those changes!

**Comment by ob6160** [comment]
> Just opened a new PR with those changes!

Nice one, just linking the new one for posterity #1401  closing this PR for now and will review new one soon

**Pull request closed without merging**
