### PR TITLE
Use a custom cluster marker style

### PR DESCRIPTION
**Pull request by mxdvl**
## What does this change?

| Before | After |
|--------|--------|
| before | after |

## How was this tested?

How have you tested your changes?

- Locally with `pnpm dev`

## Accessibility

If applicable to your changes, have you:

- [ ] Tested with screen reader
- [ ] Checked to see if navigable by keyboard
- [X] Ensured that the colour contrast is passing

## Documentation

If applicable to your changes, have you:

- [ ] Added/edited the appropriate documentation
- [ ] Added any component(s) to Storybook

### CODE REVIEW

**Review by marxian — APPROVED** [review]
This looks great!

Thanks @mxdvl

**Comment by mxdvl** [comment]
I’ve accepted the Chromatic diffs as they were only changes to the OSM map updates – but there isn’t a story capturing the marker styles. Should I create one?

**Comment by ob6160** [comment]
> I’ve accepted the Chromatic diffs as they were only changes to the OSM map updates – but there isn’t a story capturing the marker styles. Should I create one?

If it’s not too much extra effort to chuck in an extra map story with a marker cluster on it there’s no harm IMO. 

 I’m not massively bothered though as it should be quite obvious very quickly when testing if clusters look off if we capture it in Chromatic or not as it’s so core to the experience. Happy either way :)

**Comment by mxdvl** [comment]
> If it’s not too much extra effort to chuck in an extra map story with a marker cluster on it there’s no harm IMO.

I’ve tried a few things, but I’m not understanding how to add marker groups to a story, so I’d prefer getting this in first and possibly improving this as a follow up.

**Comment by ob6160** [comment]
> > If it’s not too much extra effort to chuck in an extra map story with a marker cluster on it there’s no harm IMO.
> 
> I’ve tried a few things, but I’m not understanding how to add marker groups to a story, so I’d prefer getting this in first and possibly improving this as a follow up.

sounds good - let's merge it!

👏 first loo map contribution 🚽

**Pull request merged**
